### ISSUE TITLE
Round Icons

### ISSUE THREAD

**Issue by trymeouteh** [Cryptofonts/cryptofont#25]
Please create a round icon like the _cf-btc_ icon but for the following coins

Bitcoin Cash (BCH)
Litecoin (LTC)
Dash (DASH)
Ethereum (ETH)
Haven (XHV)
LBRY Credits (LBC)
Firo (Firo)

**Comment by monzanifabio** [comment]
Round icons for all coins should come in release 3.0 which is not far away.
